### ISSUE TITLE
[BUG] `sits_accuracy()` produces error when samples labels do not match cube labels

### ISSUE THREAD

**Issue by OldLipe** [e-sensing/sits#1004]
**Describe the bug**
The error is: `Error: .sits_accuracy_area_assess: Mismatch between error matrix and area vector. (unique(dim(error_matrix)) == length(area) is not TRUE)`

**To Reproduce**
```R
library(sits)

rf_model <- sits_train(samples_modis_ndvi, ml_method = sits_rfor)

data_dir <- system.file("extdata/raster/mod13q1", package = "sits")

cube <- sits_cube(
    source = "BDC",
    collection = "MOD13Q1-6",
    data_dir = data_dir
)

probs_cube <- sits_classify(
    data = cube,
    ml_model = rf_model,
    output_dir = tempdir(),
    version = "ex_classify"
)

label_cube <- sits_label_classification(
    probs_cube,
    output_dir = tempdir()
)

reclass <- sits_reclassify(
    cube = label_cube,
    mask = label_cube,
    rules = list(
        Cerrado = mask %in% c("Pasture", "Cerrado")
    ),
    output_dir = tempdir()
)

sits_accuracy(
    data = reclass, validation = samples_modis_ndvi
)
```

The fix should remove classes that are not in cube labels.

**Comment by LorisDeBiasi** [comment]
Hi, I had this issue and after updating to sits/dev I'm now getting `Error: sits_accuracy: predicted and reference vector do not match (length(reference) == length(predicted) is not TRUE)`

After digging for a bit, I found out that `predicted` is empty (`predicted <- labels_cube[.as_chr(unlist(values))]`)

`labels_cube` contains labels (as it should I guess), and `values` contains numerical values. (values below).

After digging a bit more I found out that  `values` contains `NA` value and the issue seems to be coming from here.

By any chance, do you have any idea where this could be coming from ?

I don't know if it's a bug or if the problem comes from my side which is why I'm asking.

```
> labels_cube
                                         1 
                            "Brush forest" 
                                         2 
                           "Brush meadows" 
                                         3 
                               "Buildings" 
                                         4 
                           "Closed forest" 
                                         5 
                       "Clusters of trees" 
                                         6 
                   "Consolidated surfaces" 
                                         7 
                            "Forest edges" 
                                         8 
                           "Forest strips" 
                                         9 
"Gardens with border and patch structures" 
                                        10 
                 "Glacier, perpetual snow" 
                                        11 
                           "Granular soil" 
                                        12 
               "Grass and herb vegetation" 
                                        13 
                             "Greenhouses" 
                                        14 
                                   "Lawns" 
                                        15 
                            "Linear woods" 
                                        16 
                 "Mix of small structures" 
                                        17 
                             "Open forest" 
                                        18 
 "Permanent garden plants and brush crops" 
                                        19 
                           "Reedy marshes" 
                                        20 
                             "Rocky areas" 
                                        21 
                  "Short-stem fruit trees" 
                                        22 
                                  "Shrubs" 
                                        23 
                              "Solid rock"
                                        24 
                                   "Vines" 
                                        25 
                                   "Water" 
                                        26 
                                "Wetlands"
```


```
> values
      lyr.1
1        12
2        12
3        12
4        12
5        12
6        12
7        25
8        12
9         6
10       12
11        4
12       12
13       12
14       12
15       12
16        4
17        4
18        6
19       12
20       12
21        4
22        4
23        4
24        4
25       26
26       26
27       26
28       25
29       25
30       25
31       25
32        6
33       25
34       25
35       25
36       25
37       12
38        4
39        4
40        4
41        4
42       12
43       12
44       12
45       12
46       12
47       12
48       25
49       25
50       12
51       12
52       12
53       12
54       12
55       12
56       12
57        4
58       25
59       12
60       12
61       25
62        4
63       12
64       12
65       12
66       12
67       12
68       12
69       12
70       12
71       12
72       12
73       12
74       12
75       12
76       12
77       12
78       12
79       12
80       12
81       12
82       12
83       12
84       12
85       12
86       12
87        4
88        4
89        4
90       26
91       25
92       25
93       25
94       25
95       25
96       25
97       25
98       25
99       25
100      25
.
.
.
```

**Comment by gilbertocamara** [comment]
Hi @LorisDeBiasi this is a bug in SITS that has been fixed in version 1.4.2, which will be sent to CRAN shortly. Meanwhile, you can download version 1.4.2 directly from github as follo2w
`devtools::install_github("e-sensing/sits@dev")

**Comment by LorisDeBiasi** [comment]
Hi @gilbertocamara, thank you for your response. I already switched to 1.4.2 but I'm guessing that I need to rerun sits_classify and sits_label_classification.

**Comment by OldLipe** [comment]
Dear @LorisDeBiasi, 

After installing a new version, it is necessary to restart the current session for the update to be applied. Let us know if the bug still persists.

**Comment by LorisDeBiasi** [comment]
Hi @OldLipe, I'm sorry maybe it wasn't clear. I ran everything in 1.4.1 (sits_cube, sits_cube_copy, sits_regularize, sits_train, sits_classify, sits_smooth, sits_label_classification) and got the error in this issue when running `sits_accuracy`.

I than updated to 1.4.2 and only ran `sits_accuracy` again (since I still have the output of all the other steps) and this time I got `Error: sits_accuracy: predicted and reference vector do not match (length(reference) == length(predicted) is not TRUE)` (the error from my first comment).

What I said in my previous comment is that I guess that I also have to run `sits_classify` and `sits_label_classification` (which seems to be linked to #994 and #964).

**Comment by LorisDeBiasi** [comment]
After rerunning `sits_classify` and `sits_label_classification` I'm still getting the error `Error: .sits_accuracy_area_assess: Mismatch between error matrix and area vector. (unique(dim(error_matrix)) == length(area) is not TRUE)` even tough I'm on 1.4.2.

Here are my error_matrix, area and sessionInfo()

I can send you the rds if you want, but from what I see shouldn't the empty labels be removed ?
```
> error_matrix
                                          
                                           Brush forest Brush meadows Buildings
  Brush forest                                        0             0         0
  Brush meadows                                       0             0         0
  Buildings                                           0             0         0
  Closed forest                                    1877          1173        87
  Clusters of trees                                   0             0         0
  Consolidated surfaces                               5           335     10136
  Forest edges                                        0             0         0
  Forest strips                                       0             0         0
  Gardens with border and patch structures            0             0         0
  Glacier, perpetual snow                             0             0         0
  Granular soil                                       0             0         0
  Grass and herb vegetation                        1367          3257      1231
  Greenhouses                                         0             0         0
  Lawns                                               0             0         0
  Linear woods                                        0             0         0
  Mix of small structures                             0             0         0
  Open forest                                         0             0         0
  Permanent garden plants and brush crops             0             0         0
  Reedy marshes                                       0             0         0
  Rocky areas                                         0             0         0
  Short-stem fruit trees                              0             0         0
  Shrubs                                              0             0         0
  Solid rock                                          7            35        31
  Undefined                                           0             0         0
  Vines                                               2            17        17
  Water                                               0             6        13
  Wetlands                                            0             0         0
                                          
                                           Closed forest Clusters of trees
  Brush forest                                         0                 0
  Brush meadows                                        0                 0
  Buildings                                            0                 0
  Closed forest                                   167635              3496
  Clusters of trees                                    0                 0
  Consolidated surfaces                              184               880
  Forest edges                                         0                 0
  Forest strips                                        0                 0
  Gardens with border and patch structures             0                 0
  Glacier, perpetual snow                              0                 2
  Granular soil                                        0                 0
  Grass and herb vegetation                         2137              8605
  Greenhouses                                          0                 0
  Lawns                                                0                 0
  Linear woods                                         0                 0
  Mix of small structures                              0                 0
  Open forest                                          0                 0
  Permanent garden plants and brush crops              0                 0
  Reedy marshes                                        0                 0
  Rocky areas                                          0                 0
  Short-stem fruit trees                               0                 0
  Shrubs                                               0                 0
  Solid rock                                          21                19
  Undefined                                            0                 0
  Vines                                                1                46
  Water                                               22                14
  Wetlands                                             0                 0
                                          
                                           Consolidated surfaces Forest edges
  Brush forest                                                 0            0
  Brush meadows                                                0            0
  Buildings                                                    0            0
  Closed forest                                             2028          421
  Clusters of trees                                            0            0
  Consolidated surfaces                                    23550           34
  Forest edges                                                 0            0
  Forest strips                                                0            0
  Gardens with border and patch structures                     0            0
  Glacier, perpetual snow                                      0            0
  Granular soil                                                0            0
  Grass and herb vegetation                                10290          686
  Greenhouses                                                  0            0
  Lawns                                                        0            0
  Linear woods                                                 0            0
  Mix of small structures                                      0            0
  Open forest                                                  0            0
  Permanent garden plants and brush crops                      0            0
  Reedy marshes                                                0            0
  Rocky areas                                                  0            0
  Short-stem fruit trees                                       0            0
  Shrubs                                                       0            0
  Solid rock                                                  45            0
  Undefined                                                    0            0
  Vines                                                      273            0
  Water                                                      119            4
  Wetlands                                                     0            0
                                          
                                           Forest strips
  Brush forest                                         0
  Brush meadows                                        0
  Buildings                                            0
  Closed forest                                     4733
  Clusters of trees                                    0
  Consolidated surfaces                              144
  Forest edges                                         0
  Forest strips                                        0
  Gardens with border and patch structures             0
  Glacier, perpetual snow                              0
  Granular soil                                        0
  Grass and herb vegetation                         1546
  Greenhouses                                          0
  Lawns                                                0
  Linear woods                                         0
  Mix of small structures                              0
  Open forest                                          0
  Permanent garden plants and brush crops              0
  Reedy marshes                                        0
  Rocky areas                                          0
  Short-stem fruit trees                               0
  Shrubs                                               0
  Solid rock                                           2
  Undefined                                            0
  Vines                                                4
  Water                                               10
  Wetlands                                             0
                                          
                                           Gardens with border and patch structures
  Brush forest                                                                    0
  Brush meadows                                                                   0
  Buildings                                                                       0
  Closed forest                                                                  27
  Clusters of trees                                                               0
  Consolidated surfaces                                                         978
  Forest edges                                                                    0
  Forest strips                                                                   0
  Gardens with border and patch structures                                        0
  Glacier, perpetual snow                                                         0
  Granular soil                                                                   0
  Grass and herb vegetation                                                     559
  Greenhouses                                                                     0
  Lawns                                                                           0
  Linear woods                                                                    0
  Mix of small structures                                                         0
  Open forest                                                                     0
  Permanent garden plants and brush crops                                         0
  Reedy marshes                                                                   0
  Rocky areas                                                                     0
  Short-stem fruit trees                                                          0
  Shrubs                                                                          0
  Solid rock                                                                      2
  Undefined                                                                       0
  Vines                                                                          15
  Water                                                                           0
  Wetlands                                                                        0
                                          
                                           Glacier, perpetual snow
  Brush forest                                                 235
  Brush meadows                                                  0
  Buildings                                                      0
  Closed forest                                                  0
  Clusters of trees                                              0
  Consolidated surfaces                                        115
  Forest edges                                                   0
  Forest strips                                                  0
  Gardens with border and patch structures                       0
  Glacier, perpetual snow                                      747
  Granular soil                                                  0
  Grass and herb vegetation                                      1
  Greenhouses                                                    0
  Lawns                                                          0
  Linear woods                                                   0
  Mix of small structures                                        0
  Open forest                                                    0
  Permanent garden plants and brush crops                        0
  Reedy marshes                                                  0
  Rocky areas                                                    0
  Short-stem fruit trees                                         0
  Shrubs                                                         0
  Solid rock                                                   312
  Undefined                                                      0
  Vines                                                          0
  Water                                                          8
  Wetlands                                                       0
                                          
                                           Granular soil
  Brush forest                                       276
  Brush meadows                                        0
  Buildings                                            0
  Closed forest                                      533
  Clusters of trees                                    0
  Consolidated surfaces                             4842
  Forest edges                                         0
  Forest strips                                        0
  Gardens with border and patch structures             0
  Glacier, perpetual snow                            448
  Granular soil                                        0
  Grass and herb vegetation                         2215
  Greenhouses                                          0
  Lawns                                                0
  Linear woods                                         0
  Mix of small structures                              0
  Open forest                                          0
  Permanent garden plants and brush crops              0
  Reedy marshes                                        0
  Rocky areas                                          0
  Short-stem fruit trees                               0
  Shrubs                                               0
  Solid rock                                        2194
  Undefined                                            0
  Vines                                               18
  Water                                              237
  Wetlands                                             0
                                          
                                           Grass and herb vegetation
  Brush forest                                                     0
  Brush meadows                                                    0
  Buildings                                                        0
  Closed forest                                                 4814
  Clusters of trees                                                0
  Consolidated surfaces                                         4912
  Forest edges                                                     0
  Forest strips                                                    0
  Gardens with border and patch structures                         0
  Glacier, perpetual snow                                          1
  Granular soil                                                    0
  Grass and herb vegetation                                   311977
  Greenhouses                                                      0
  Lawns                                                            0
  Linear woods                                                     0
  Mix of small structures                                          0
  Open forest                                                      0
  Permanent garden plants and brush crops                          0
  Reedy marshes                                                    0
  Rocky areas                                                      0
  Short-stem fruit trees                                           0
  Shrubs                                                           0
  Solid rock                                                     129
  Undefined                                                        0
  Vines                                                          237
  Water                                                           49
  Wetlands                                                         0
                                          
                                           Greenhouses  Lawns Linear woods
  Brush forest                                       0      0            0
  Brush meadows                                      0      0            0
  Buildings                                          0      0            0
  Closed forest                                      2    412         1200
  Clusters of trees                                  0      0            0
  Consolidated surfaces                            241   4115          855
  Forest edges                                       0      0            0
  Forest strips                                      0      0            0
  Gardens with border and patch structures           0      0            0
  Glacier, perpetual snow                            0      0            0
  Granular soil                                      0      0            0
  Grass and herb vegetation                         71   1407         6356
  Greenhouses                                        0      0            0
  Lawns                                              0      0            0
  Linear woods                                       0      0            0
  Mix of small structures                            0      0            0
  Open forest                                        0      0            0
  Permanent garden plants and brush crops            0      0            0
  Reedy marshes                                      0      0            0
  Rocky areas                                        0      0            0
  Short-stem fruit trees                             0      0            0
  Shrubs                                             0      0            0
  Solid rock                                         9      1            0
  Undefined                                          0      0            0
  Vines                                              0     24           46
  Water                                              7     19           56
  Wetlands                                           0      0            0
                                          
                                           Mix of small structures Open forest
  Brush forest                                                   0           0
  Brush meadows                                                  0           0
  Buildings                                                      0           0
  Closed forest                                                 66       13343
  Clusters of trees                                              0           0
  Consolidated surfaces                                       2816         106
  Forest edges                                                   0           0
  Forest strips                                                  0           0
  Gardens with border and patch structures                       0           0
  Glacier, perpetual snow                                        0           0
  Granular soil                                                  0           0
  Grass and herb vegetation                                    633        1266
  Greenhouses                                                    0           0
  Lawns                                                          0           0
  Linear woods                                                   0           0
  Mix of small structures                                        0           0
  Open forest                                                    0           0
  Permanent garden plants and brush crops                        0           0
  Reedy marshes                                                  0           0
  Rocky areas                                                    0           0
  Short-stem fruit trees                                         0           0
  Shrubs                                                         0           0
  Solid rock                                                     0           7
  Undefined                                                      0           0
  Vines                                                         26          15
  Water                                                          6           2
  Wetlands                                                       0           0
                                          
                                           Permanent garden plants and brush crops
  Brush forest                                                                   0
  Brush meadows                                                                  0
  Buildings                                                                      0
  Closed forest                                                                 77
  Clusters of trees                                                              0
  Consolidated surfaces                                                         61
  Forest edges                                                                   0
  Forest strips                                                                  0
  Gardens with border and patch structures                                       0
  Glacier, perpetual snow                                                        0
  Granular soil                                                                  0
  Grass and herb vegetation                                                    436
  Greenhouses                                                                    0
  Lawns                                                                          0
  Linear woods                                                                   0
  Mix of small structures                                                        0
  Open forest                                                                    0
  Permanent garden plants and brush crops                                        0
  Reedy marshes                                                                  0
  Rocky areas                                                                    0
  Short-stem fruit trees                                                         0
  Shrubs                                                                         0
  Solid rock                                                                     0
  Undefined                                                                      0
  Vines                                                                          5
  Water                                                                         12
  Wetlands                                                                       0
                                          
                                           Reedy marshes Rocky areas
  Brush forest                                         0           2
  Brush meadows                                        0           0
  Buildings                                            0           0
  Closed forest                                      424         379
  Clusters of trees                                    0           0
  Consolidated surfaces                               20         916
  Forest edges                                         0           0
  Forest strips                                        0           0
  Gardens with border and patch structures             0           0
  Glacier, perpetual snow                              0           5
  Granular soil                                        0           0
  Grass and herb vegetation                          342        4270
  Greenhouses                                          0           0
  Lawns                                                0           0
  Linear woods                                         0           0
  Mix of small structures                              0           0
  Open forest                                          0           0
  Permanent garden plants and brush crops              0           0
  Reedy marshes                                        0           0
  Rocky areas                                          0           0
  Short-stem fruit trees                               0           0
  Shrubs                                               0           0
  Solid rock                                           0         637
  Undefined                                            0           0
  Vines                                                1          18
  Water                                              123          11
  Wetlands                                             0           0
                                          
                                           Short-stem fruit trees Shrubs
  Brush forest                                                  0      0
  Brush meadows                                                 0      0
  Buildings                                                     0      0
  Closed forest                                               145   5343
  Clusters of trees                                             0      0
  Consolidated surfaces                                       299    290
  Forest edges                                                  0      0
  Forest strips                                                 0      0
  Gardens with border and patch structures                      0      0
  Glacier, perpetual snow                                       0      0
  Granular soil                                                 0      0
  Grass and herb vegetation                                  1061   2447
  Greenhouses                                                   0      0
  Lawns                                                         0      0
  Linear woods                                                  0      0
  Mix of small structures                                       0      0
  Open forest                                                   0      0
  Permanent garden plants and brush crops                       0      0
  Reedy marshes                                                 0      0
  Rocky areas                                                   0      0
  Short-stem fruit trees                                        0      0
  Shrubs                                                        0      0
  Solid rock                                                    0     25
  Undefined                                                     0      0
  Vines                                                        52     14
  Water                                                         0     23
  Wetlands                                                      0      0
                                          
                                           Solid rock Undefined  Vines  Water
  Brush forest                                    381         0      0      0
  Brush meadows                                     0         0      0      0
  Buildings                                         0         0      0      0
  Closed forest                                   434       208     76    656
  Clusters of trees                                 0         0      0      0
  Consolidated surfaces                          2597      6890    463    330
  Forest edges                                      0         0      0      0
  Forest strips                                     0         0      0      0
  Gardens with border and patch structures          0         0      0      0
  Glacier, perpetual snow                         332         0      0      4
  Granular soil                                     0         0      0      0
  Grass and herb vegetation                      1014      4100    607    491
  Greenhouses                                       0         0      0      0
  Lawns                                             0         0      0      0
  Linear woods                                      0         0      0      0
  Mix of small structures                           0         0      0      0
  Open forest                                       0         0      0      0
  Permanent garden plants and brush crops           0         0      0      0
  Reedy marshes                                     0         0      0      0
  Rocky areas                                       0         0      0      0
  Short-stem fruit trees                            0         0      0      0
  Shrubs                                            0         0      0      0
  Solid rock                                     2714         1      0     22
  Undefined                                         0         0      0      0
  Vines                                             4        40   6390      0
  Water                                            69        10      0  83007
  Wetlands                                          0         0      0      0
                                          
                                           Wetlands
  Brush forest                                    0
  Brush meadows                                   0
  Buildings                                       0
  Closed forest                                 363
  Clusters of trees                               0
  Consolidated surfaces                          15
  Forest edges                                    0
  Forest strips                                   0
  Gardens with border and patch structures        0
  Glacier, perpetual snow                         0
  Granular soil                                   0
  Grass and herb vegetation                    1074
  Greenhouses                                     0
  Lawns                                           0
  Linear woods                                    0
  Mix of small structures                         0
  Open forest                                     0
  Permanent garden plants and brush crops         0
  Reedy marshes                                   0
  Rocky areas                                     0
  Short-stem fruit trees                          0
  Shrubs                                          0
  Solid rock                                      0
  Undefined                                       0
  Vines                                           0
  Water                                          26
  Wetlands                                        0
```

```
> area
             Brush forest             Closed forest     Consolidated surfaces 
                 74208.92                4562786.33                1659572.94 
  Glacier, perpetual snow Grass and herb vegetation                Solid rock 
                179294.98                5827513.03                 519438.83 
                    Vines                     Water 
                 23946.20                 414882.77 
```

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /opt/ebsofts/FlexiBLAS/3.2.0-foss-2022a/lib64/libflexiblas.so.3.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11        lubridate_1.9.3    here_1.0.1         class_7.3-20      
 [5] prettyunits_1.2.0  sysfonts_0.8.8     ps_1.7.5           rprojroot_2.0.3   
 [9] digest_0.6.33      utf8_1.2.3         mime_0.12          R6_2.5.1          
[13] e1071_1.7-13       pillar_1.9.0       rlang_1.1.1        curl_5.1.0        
[17] data.table_1.14.8  miniUI_0.1.1.1     callr_3.7.3        urlchecker_1.0.1  
[21] slider_0.3.0       desc_1.4.2         devtools_2.4.5     stringr_1.5.0     
[25] htmlwidgets_1.6.2  sits_1.4.2         proxy_0.4-27       shiny_1.7.5       
[29] compiler_4.2.1     httpuv_1.6.11      pkgconfig_2.0.3    pkgbuild_1.4.2    
[33] htmltools_0.5.6    tidyselect_1.2.0   tibble_3.2.1       codetools_0.2-19  
[37] fansi_1.0.5        crayon_1.5.2       showtextdb_3.0     dplyr_1.1.3       
[41] later_1.3.1        sf_1.0-14          grid_4.2.1         jsonlite_1.8.7    
[45] xtable_1.8-4       lifecycle_1.0.3    DBI_1.1.3          magrittr_2.0.3    
[49] units_0.8-4        modules_0.11.0     KernSmooth_2.23-20 warp_0.2.0        
[53] cli_3.6.1          stringi_1.7.12     cachem_1.0.8       argparse_2.2.2    
[57] fs_1.6.3           promises_1.2.1     remotes_2.4.2.1    ellipsis_0.3.2    
[61] generics_0.1.3     vctrs_0.6.3        tools_4.2.1        showtext_0.9-6    
[65] glue_1.6.2         purrr_1.0.2        processx_3.8.2     pkgload_1.3.3     
[69] fastmap_1.1.1      yaml_2.3.7         timechange_0.2.0   terra_1.7-46      
[73] sessioninfo_1.2.2  classInt_0.4-10    memoise_2.0.1      profvis_0.3.8     
[77] usethis_2.2.2
```

**Comment by OldLipe** [comment]
Dear @LorisDeBiasi,

Would you have a time to have a teleconference this week? We would like to better understand your problem so we will be able to help you.

Best.

**Comment by LorisDeBiasi** [comment]
Hi @OldLipe,

I'm available Wednesday and Thursday this week from 8am UTC to 4pm UTC, would that be okay with you? Otherwise, I will be available from Tuesday to Thursday next week.

Regards.

**Comment by gilbertocamara** [comment]
Dear @LorisDeBiasi, we propose to meet on Wednesday, October 10th, at 14:00 UTC (which wil be 11:00 BRT). Please use the following link to connect:
https://us02web.zoom.us/j/3347971699

**Comment by LorisDeBiasi** [comment]
Dear @OldLipe and @gilbertocamara,

I'm really sorry but I forgot that the cluster I'm working on will be under maintenance from today until at least Friday and all the data are on it. If you just want to see the code and/or sample/validation csv we can maintain the meeting, but if you'd like to explore the data we should postpone.

Regards.

**Comment by gilbertocamara** [comment]
Dear @LorisDeBiasi, it would be better to postpone the meeting. What would be an appropriate time for you?

**Comment by LorisDeBiasi** [comment]
@gilbertocamara I'm available the 18th and 19th October from 8:00 UTC to 16:00 UTC. I hope that the maintenance will be over by then

**Comment by LorisDeBiasi** [comment]
Dear @gilbertocamara and @OldLipe, the cluster is back online. I'm sorry again for the oversight on my part. Let me know when you prefer to do the teleconference
